---
title: "16S_daily"
format:
  html:
    theme: default
---

# Getting Started:

#### Libraries

```{r, include=FALSE}
library(tidyverse)
library(here)
library(vegan)
library(viridis)
library(cowplot)
```

#### Load Clean 16S data

```{r}
ps<- readRDS(file = here("data", "clean_data", "clean_16s_phyloseq_Daily.rds"))
```

# Cleaning

#### Make Top### Dataframe

```{r}
topN <- names(sort(taxa_sums(ps), decreasing=TRUE))[1:300] #Selects top N to look at
ps.topN <- transform_sample_counts(ps, function(OTU) OTU/sum(OTU))
ps.topN <- prune_taxa(topN, ps.topN)
```

#### Make into DF so we can manipulate

```{r}
data<- psmelt(ps.topN)
```

#### Make Date a `Date` variable

```{r}
data<-
  data %>%
mutate(Date = case_when( Date == "7_" ~ "2022-07-07",
                          Date == "8_" ~ "2022-07-08",
                          Date == "9_" ~ "2022-07-09",
                          Date == "11" ~ "2022-07-11",
                          Date == "12" ~ "2022-07-12",
                          Date == "13" ~ "2022-07-13",
                          Date == "14" ~ "2022-07-14",
                          Date == "15" ~ "2022-07-15",
                          Date == "16" ~ "2022-07-16",
                          Date == "17" ~ "2022-07-17",
                          Date == "18" ~ "2022-07-18",
                          Date == "19" ~ "2022-07-19")) 
data<- data %>%
  mutate(Date = as.Date(data$Date))
```

# Visualization

## Community Composition

https://www.rpubs.com/roalle/mres_2019

#### Stacked Barplot

```{r, fig.width=12, fig.height=7}
data %>% 
  filter(Site %in% c("BO", "C2", "RD")) %>% #Gets rid of Positive Controls
    ggplot() + geom_bar(
  aes(x = Date,
      y = Abundance,
      fill = Family),
  color = "black",
  stat = "identity") +
  facet_wrap(~Site, scales = "free_x")+
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1),
    #legend.position = "none"
    ) +
  scale_x_date(date_breaks = "1 day", date_labels = "%b%d") 
```

##### Stacked Barplot: Look at just Borchardt

```{r}
vib<- data %>% 
  filter(Family %in% c("Vibrionaceae", "Rhodobacteraceae", "Flavobacteriaceae", "Cryomorphaceae"),
         !Site %in% "gu") 

vib %>% ggplot() + geom_bar(
  aes(x = Date,
      y = Abundance,
      fill = Family),
  color = "black",
  stat = "identity") +
  facet_wrap(~Site, scales = "free_x")+
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1)) +
  scale_x_date(date_breaks = "1 day", date_labels = "%b%d") 
```

## 
